ARG RUBY_VERSION=3.4.10
FROM ruby:$RUBY_VERSION-slim

ENV LANG=C.UTF-8 \
    TZ=Asia/Ho_Chi_Minh \
    RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      libjemalloc2 \
      libpq-dev \
      libvips \
      libyaml-dev \
      pkg-config \
      postgresql-client \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

ENV LD_PRELOAD=libjemalloc.so.2

ARG RAILS_VERSION=8.1.3.1
RUN gem update --system --no-document \
 && gem install rails -v $RAILS_VERSION --no-document

WORKDIR /rails
EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
