development:
  adapter: solid_cable
  polling_interval: 1.second
  message_retention: 1.day

test:
  adapter: test

production:
  adapter: solid_cable
  polling_interval: 1.second
  message_retention: 1.day

staging:
  adapter: solid_cable
  polling_interval: 1.second
  message_retention: 1.day
