service: travelog

image: travelog

servers:
  web:
    - 18.139.214.198

proxy:
  ssl: true
  host: travelog-ac.duckdns.org
  app_port: 80
  healthcheck:
    path: /up
    interval: 5
    timeout: 60

registry:
  server: 757876532307.dkr.ecr.ap-southeast-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: arm64

asset_path: /rails/public/assets

ssh:
  user: ec2-user

retain_containers: 2

deploy_timeout: 120
drain_timeout: 30

logging:
  driver: json-file
  options:
    max-size: 50m
    max-file: 3

env:
  clear:
    RAILS_MAX_THREADS: 3
    SOLID_QUEUE_IN_PUMA: 1
    JOB_CONCURRENCY: 1
    DB_POOL: 8

    POSTGRES_HOST: travelog-db
    POSTGRES_PORT: 5432
    POSTGRES_DB: travelog_production
    POSTGRES_USER: travelog

    APP_HOST: travelog-ac.duckdns.org
    APP_PROTOCOL: https

    CDN_HOST: https://d18cfkqnlgph1i.cloudfront.net
    S3_BUCKET_ORIGINALS: travelog-originals-production
    S3_BUCKET_DERIVATIVES: travelog-derivatives-production
    AWS_REGION: ap-southeast-1
    MAILER_SENDER: no-reply@travelog-ac.duckdns.org

    GOOGLE_MAPS_MAP_ID: "42b44844963e83deb9f3a013"
    RAILS_LOG_LEVEL: info

  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - GOOGLE_MAPS_API_KEY
    - GOOGLE_MAPS_BROWSER_KEY

accessories:
  db:
    image: postgres:17-alpine
    host: 18.139.214.198
    env:
      clear:
        POSTGRES_USER: travelog
        POSTGRES_DB: travelog_production
        LANG: C.UTF-8
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/travelog/postgres:/var/lib/postgresql/data
    options:
      shm-size: 256m
    cmd: >-
      postgres
      -c max_connections=30
      -c shared_buffers=192MB
      -c effective_cache_size=640MB
      -c work_mem=8MB
      -c maintenance_work_mem=64MB
      -c wal_buffers=8MB
      -c max_wal_size=512MB
      -c min_wal_size=128MB
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c jit=off
      -c max_parallel_workers_per_gather=0
      -c max_parallel_workers=0
      -c autovacuum_naptime=30s
      -c autovacuum_vacuum_scale_factor=0.05
      -c autovacuum_analyze_scale_factor=0.05
      -c log_min_duration_statement=500
      -c log_checkpoints=on

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs --follow
  dbc: accessory exec db --interactive --reuse "psql -U travelog -d travelog_production"
  migrate: app exec "bin/rails db:migrate"
