base_locale: vi
locales: [vi, en]

data:
  read:
    - config/locales/%{locale}.yml
  write:
    - config/locales/%{locale}.yml

search:
  paths:
    - app/
  relative_roots:
    - app/views
    - app/controllers
    - app/helpers
  exclude:
    - "**/*.md"

ignore_unused:
  - status.*
  - review.*
  - filters.state.*
  - place_type.*
  - tag_kind.*
  - filters.sort.*
  - locale_name.*
  - date.formats.*
  - time.formats.*
  - activerecord.*

ignore_missing:
  - date.month_names
