<%
  s3 = Rails.application.config.settings.s3
%>
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

originals:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= s3.region %>
  bucket: <%= s3.bucket_originals %>
  upload:
    server_side_encryption: AES256

derivatives:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= s3.region %>
  bucket: <%= s3.bucket_derivatives %>
